server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: provider
dubbo:
  scan:
    base-packages: io.github.spafka
  protocol:
    name: tri
    port: 20880
  application:
    compiler: jdk

  registry:
    address: nacos://localhost:8848

#  registry:
#    id: zk-registry
#    address: zookeeper://127.0.0.1:2181
#    config-center:
#      address: zookeeper://127.0.0.1:2181
#    metadata-report:
#      address: zookeeper://127.0.0.1:2181
  provider:
    proxy: jdk


